require('dotenv').config();

const config : any = {
    baseURL: process.env.BASE_URL,
    env: process.env.NODE_ENV,
    port: process.env.PORT || 3000,
    mysql: {
        username: process.env.SQL_DB_USERNAME,
        password: process.env.SQL_DB_PASSWORD,
        databaseName: process.env.MYSQL_DB_DATABASE_NAME,
        host: process.env.MYSQL_DB_HOST,
        port: process.env.MYSQL_DB_PORT,
        dialect: 'mysql',
        timezone: '+06:00',
        operatorsAliases: false
    },
    redis: {
        host: process.env.REDIS_HOST,
        port: process.env.REDIS_PORT,
        pass: process.env.REDIS_PASS
    },
    passphrase: process.env.secretKey,
    mail: {
        host: process.env.SMTP_HOST,
        port: 465,
        secure: true, // true for 465, false for other ports
        auth: {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASSWORD
        }
    },
    EXCHANGE_PROVIDER: process.env.EXCHANGE_PROVIDER,
    
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_GCC_SECRET_KEY: process.env.STRIPE_GCC_SECRET_KEY,

    PHANTOM_JS_PATH: process.env.PHANTOM_JS_PATH,
    
    DOMAIN_COM_YEARLY: process.env.DOMAIN_COM_YEARLY,
    STARTER_WEB_HOSTING_MONTHLY_DEV: process.env.STARTER_WEB_HOSTING_MONTHLY_DEV,
    STARTER_WEB_HOSTING_MONTHLY: process.env.STARTER_WEB_HOSTING_MONTHLY,
    STARTER_WEB_HOSTING_QUARTERLY: process.env.STARTER_WEB_HOSTING_QUARTERLY,
    STARTER_WEB_HOSTING_YEARLY: process.env.STARTER_WEB_HOSTING_YEARLY,

    PRO_WEB_HOSTING_MONTHLY: process.env.PRO_WEB_HOSTING_MONTHLY,
    PRO_WEB_HOSTING_QUARTERLY: process.env.PRO_WEB_HOSTING_QUARTERLY,
    PRO_WEB_HOSTING_YEARLY: process.env.PRO_WEB_HOSTING_YEARLY,

    ULTIMATE_WEB_HOSTING_MONTHLY: process.env.ULTIMATE_WEB_HOSTING_MONTHLY,
    ULTIMATE_WEB_HOSTING_QUARTERLY: process.env.ULTIMATE_WEB_HOSTING_QUARTERLY,
    ULTIMATE_WEB_HOSTING_YEARLY: process.env.ULTIMATE_WEB_HOSTING_YEARLY,

    MAX_WEB_HOSTING_MONTHLY: process.env.MAX_WEB_HOSTING_MONTHLY,
    MAX_WEB_HOSTING_QUARTERLY: process.env.MAX_WEB_HOSTING_QUARTERLY,
    MAX_WEB_HOSTING_YEARLY: process.env.MAX_WEB_HOSTING_YEARLY,

    STARTER_WORDPRESS_HOSTING_MONTHLY_DEV: process.env.STARTER_WORDPRESS_HOSTING_MONTHLY_DEV,
    STARTER_WORDPRESS_HOSTING_MONTHLY: process.env.STARTER_WORDPRESS_HOSTING_MONTHLY,
    STARTER_WORDPRESS_HOSTING_QUARTERLY: process.env.STARTER_WORDPRESS_HOSTING_QUARTERLY,
    STARTER_WORDPRESS_HOSTING_YEARLY: process.env.STARTER_WORDPRESS_HOSTING_YEARLY,

    PRO_WORDPRESS_HOSTING_MONTHLY: process.env.PRO_WORDPRESS_HOSTING_MONTHLY,
    PRO_WORDPRESS_HOSTING_QUARTERLY: process.env.PRO_WORDPRESS_HOSTING_QUARTERLY,
    PRO_WORDPRESS_HOSTING_YEARLY: process.env.PRO_WORDPRESS_HOSTING_YEARLY,

    ULTIMATE_WORDPRESS_HOSTING_MONTHLY: process.env.ULTIMATE_WORDPRESS_HOSTING_MONTHLY,
    ULTIMATE_WORDPRESS_HOSTING_QUARTERLY: process.env.ULTIMATE_WORDPRESS_HOSTING_QUARTERLY,
    ULTIMATE_WORDPRESS_HOSTING_YEARLY: process.env.ULTIMATE_WORDPRESS_HOSTING_YEARLY,

    MAX_WORDPRESS_HOSTING_MONTHLY: process.env.MAX_WORDPRESS_HOSTING_MONTHLY,
    MAX_WORDPRESS_HOSTING_QUARTERLY: process.env.MAX_WORDPRESS_HOSTING_QUARTERLY,
    MAX_WORDPRESS_HOSTING_YEARLY: process.env.MAX_WORDPRESS_HOSTING_YEARLY,

    STARTER_EMAIL_HOSTING_MONTHLY: process.env.STARTER_EMAIL_HOSTING_MONTHLY,
    STARTER_EMAIL_HOSTING_QUARTERLY: process.env.STARTER_EMAIL_HOSTING_QUARTERLY,
    STARTER_EMAIL_HOSTING_YEARLY: process.env.STARTER_EMAIL_HOSTING_YEARLY,

    PRO_EMAIL_HOSTING_MONTHLY: process.env.PRO_EMAIL_HOSTING_MONTHLY,
    PRO_EMAIL_HOSTING_QUARTERLY: process.env.PRO_EMAIL_HOSTING_QUARTERLY,
    PRO_EMAIL_HOSTING_YEARLY: process.env.PRO_EMAIL_HOSTING_YEARLY,

    ULTIMATE_EMAIL_HOSTING_MONTHLY: process.env.ULTIMATE_EMAIL_HOSTING_MONTHLY,
    ULTIMATE_EMAIL_HOSTING_QUARTERLY: process.env.ULTIMATE_EMAIL_HOSTING_QUARTERLY,
    ULTIMATE_EMAIL_HOSTING_YEARLY: process.env.ULTIMATE_EMAIL_HOSTING_YEARLY,

    MAX_EMAIL_HOSTING_MONTHLY: process.env.MAX_EMAIL_HOSTING_MONTHLY,
    MAX_EMAIL_HOSTING_QUARTERLY: process.env.MAX_EMAIL_HOSTING_QUARTERLY,
    MAX_EMAIL_HOSTING_YEARLY: process.env.MAX_EMAIL_HOSTING_YEARLY,

    TIER1_COMPUTE_ENGINE_MONTHLY: process.env.TIER1_COMPUTE_ENGINE_MONTHLY,
    TIER2_COMPUTE_ENGINE_MONTHLY: process.env.TIER2_COMPUTE_ENGINE_MONTHLY,
    TIER3_COMPUTE_ENGINE_MONTHLY: process.env.TIER3_COMPUTE_ENGINE_MONTHLY,
    TIER4_COMPUTE_ENGINE_MONTHLY: process.env.TIER4_COMPUTE_ENGINE_MONTHLY,
    TIER5_COMPUTE_ENGINE_MONTHLY: process.env.TIER5_COMPUTE_ENGINE_MONTHLY,
    TIER6_COMPUTE_ENGINE_MONTHLY: process.env.TIER6_COMPUTE_ENGINE_MONTHLY,
    TIER7_COMPUTE_ENGINE_MONTHLY: process.env.TIER7_COMPUTE_ENGINE_MONTHLY,
    TIER8_COMPUTE_ENGINE_MONTHLY: process.env.TIER8_COMPUTE_ENGINE_MONTHLY,
    TIER9_COMPUTE_ENGINE_MONTHLY: process.env.TIER9_COMPUTE_ENGINE_MONTHLY,
    TIER10_COMPUTE_ENGINE_MONTHLY: process.env.TIER10_COMPUTE_ENGINE_MONTHLY,
    TIER11_COMPUTE_ENGINE_MONTHLY: process.env.TIER11_COMPUTE_ENGINE_MONTHLY,
    TIER12_COMPUTE_ENGINE_MONTHLY: process.env.TIER12_COMPUTE_ENGINE_MONTHLY,
    TIER13_COMPUTE_ENGINE_MONTHLY: process.env.TIER13_COMPUTE_ENGINE_MONTHLY,
    TIER14_COMPUTE_ENGINE_MONTHLY: process.env.TIER14_COMPUTE_ENGINE_MONTHLY,
    TIER15_COMPUTE_ENGINE_MONTHLY: process.env.TIER15_COMPUTE_ENGINE_MONTHLY,
    TIER16_COMPUTE_ENGINE_MONTHLY: process.env.TIER16_COMPUTE_ENGINE_MONTHLY,
    TIER17_COMPUTE_ENGINE_MONTHLY: process.env.TIER17_COMPUTE_ENGINE_MONTHLY,
    TIER18_COMPUTE_ENGINE_MONTHLY: process.env.TIER18_COMPUTE_ENGINE_MONTHLY,
    TIER19_COMPUTE_ENGINE_MONTHLY: process.env.TIER19_COMPUTE_ENGINE_MONTHLY,

    COUPON_GOPRO5: process.env.COUPON_GOPRO5,
    COUPON_GOPRO6: process.env.COUPON_GOPRO6,
    DEFAULT_TAX: process.env.DEFAULT_TAX,
};

export default config;